### ISSUE TITLE
haivng trouble loading it

### ISSUE THREAD

**Issue by briancohn** [ktaegyum/react_application#2]
![image](https://user-images.githubusercontent.com/4623063/28237734-4b552344-68fb-11e7-97bc-dd07c379cbc9.png)

with these error messages

![image](https://user-images.githubusercontent.com/4623063/28237736-4e7c5218-68fb-11e7-9a15-ff3e97b5cbb7.png)

**Comment by briancohn** [comment]
i'm on the master branch :/

**Comment by ktaegyum** [comment]
@briancohn Did you push if you changed any? I don't have any problem even after I pull?

**Comment by briancohn** [comment]
fixed by re-cloning and npm install && react-native run-ios
